# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 goats_1_17_1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 16 # 1.17.1 can be built with Java 16 to Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Cache 1.17.1 Maven package
        id: cacheGoats
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.17.1-all
            restore-keys: ${{ runner.os }}-spigot-1.17.1-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.17.1
          restore-keys: ${{ runner.os }}-m2_1.17.1

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.17.1 Spigot
        id: goats
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.17.1 Spigot (Mojang)
        id: goatsMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.17.1 Spigot (Obf)
        id: goatsObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.17.1
        if: steps.goats.outputs.sucess != 'true' || steps.goatsMojang.outputs.sucess != 'true' || steps.goatsObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.17.1 --remapped
 caves_1_18_1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache 1.18.1 Maven package
        id: cacheCaves
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.18.1-all
            restore-keys: ${{ runner.os }}-spigot-1.18.1-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.18.1
          restore-keys: ${{ runner.os }}-m2_1.18.1

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.18.1 Spigot
        id: caves
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/spigot-1.18.1-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18.1 Spigot (Mojang)
        id: cavesMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/spigot-1.18.1-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18.1 Spigot (Obf)
        id: cavesObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/spigot-1.18.1-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.18.1
        if: steps.caves.outputs.sucess != 'true' || steps.cavesMojang.outputs.sucess != 'true' || steps.cavesObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.18.1 --remapped
 cliffs_1_18_2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache 1.18.2 Maven package
        id: cacheCaves
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.18.2-all
            restore-keys: ${{ runner.os }}-spigot-1.18.2-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.18.2
          restore-keys: ${{ runner.os }}-m2_1.18.2

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.18.2 Spigot
        id: caves
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/spigot-1.18.2-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18.2 Spigot (Mojang)
        id: cavesMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/spigot-1.18.2-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18.2 Spigot (Obf)
        id: cavesObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/spigot-1.18.2-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.18.2
        if: steps.caves.outputs.sucess != 'true' || steps.cavesMojang.outputs.sucess != 'true' || steps.cavesObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.18.2 --remapped
 wild_1_19:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache 1.19 Maven package
        id: cacheWild
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.19-all
            restore-keys: ${{ runner.os }}-spigot-1.19-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.19
          restore-keys: ${{ runner.os }}-m2_1.19

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.19 Spigot
        id: wild
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19 Spigot (Mojang)
        id: wildMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19 Spigot (Obf)
        id: wildObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.19
        if: steps.wild.outputs.sucess != 'true' || steps.wildMojang.outputs.sucess != 'true' || steps.wildObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.19 --remapped
 chat_1_19_3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache 1.19.3 Maven package
        id: cacheChat
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.19.3-all
            restore-keys: ${{ runner.os }}-spigot-1.19.3-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.19.3
          restore-keys: ${{ runner.os }}-m2_1.19.3

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.19.3 Spigot
        id: chat
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19.3 Spigot (Mojang)
        id: chatMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19.3 Spigot (Obf)
        id: chatObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.19
        if: steps.chat.outputs.sucess != 'true' || steps.chatMojang.outputs.sucess != 'true' || steps.chatObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.19.3 --remapped
 creative_1_19_4:
     runs-on: ubuntu-latest
     steps:
         - name: Set up JDK 17
           uses: actions/setup-java@v2
           with:
               distribution: 'temurin'
               java-version: '17'
         - name: Cache 1.19.4 Maven package
           id: cacheChat
           uses: actions/cache@v2
           with:
               path: |
                   ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/
                   ~/.m2/repository/org/spigotmc/spigot-parent/
                   ~/.m2/repository/org/spigotmc/minecraft-server/
               key: ${{ runner.os }}-spigot-1.19.4-all
               restore-keys: ${{ runner.os }}-spigot-1.19.4-all
         - name: Cache Maven packages
           id: cacheMain
           uses: actions/cache@v2
           with:
               path: ~/.m2
               key: ${{ runner.os }}-m2_1.19.4
               restore-keys: ${{ runner.os }}-m2_1.19.4

         - name: Setup BuildTools
           run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
         - name: Check 1.19.4 Spigot
           id: creative
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Check 1.19.4 Spigot (Mojang)
           id: creativeMojang
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Check 1.19.4 Spigot (Obf)
           id: creativeObf
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Build 1.19
           if: steps.chat.outputs.sucess != 'true' || steps.chatMojang.outputs.sucess != 'true' || steps.chatObf.outputs.sucess != 'true'
           run: cd BuildTools && java -jar BuildTools.jar --rev 1.19.4 --remapped
 trails_1_20:
     runs-on: ubuntu-latest
     steps:
         - name: Set up JDK 17
           uses: actions/setup-java@v2
           with:
               distribution: 'temurin'
               java-version: '17'
         - name: Cache 1.20 Maven package
           id: cacheChat
           uses: actions/cache@v2
           with:
               path: |
                   ~/.m2/repository/org/spigotmc/spigot/1.20-R0.1-SNAPSHOT/
                   ~/.m2/repository/org/spigotmc/spigot-parent/
                   ~/.m2/repository/org/spigotmc/minecraft-server/
               key: ${{ runner.os }}-spigot-1.20-all
               restore-keys: ${{ runner.os }}-spigot-1.20-all
         - name: Cache Maven packages
           id: cacheMain
           uses: actions/cache@v2
           with:
               path: ~/.m2
               key: ${{ runner.os }}-m2_1.20
               restore-keys: ${{ runner.os }}-m2_1.20

         - name: Setup BuildTools
           run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
         - name: Check 1.20 Spigot
           id: trails
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.20-R0.1-SNAPSHOT/spigot-1.20-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Check 1.20 Spigot (Mojang)
           id: trailsMojang
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.20-R0.1-SNAPSHOT/spigot-1.20-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Check 1.20 Spigot (Obf)
           id: trailsObf
           run: test -f ~/.m2/repository/org/spigotmc/spigot/1.20-R0.1-SNAPSHOT/spigot-1.20-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
         - name: Build 1.20
           if: steps.chat.outputs.sucess != 'true' || steps.chatMojang.outputs.sucess != 'true' || steps.chatObf.outputs.sucess != 'true'
           run: cd BuildTools && java -jar BuildTools.jar --rev 1.20 --remapped
 build:
    runs-on: ubuntu-latest
    needs: [goats_1_17_1,caves_1_18_1,cliffs_1_18_2,wild_1_19,chat_1_19_3,creative_1_19_4, trails_1_20]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Cache 1.17.1 Maven package
      id: cacheGoats
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.17.1-all
          restore-keys: ${{ runner.os }}-spigot-1.17.1-all
    - name: Cache 1.18.1 Maven package
      id: cacheCaves
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.18.1-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.18.1-all
          restore-keys: ${{ runner.os }}-spigot-1.18.1-all
    - name: Cache 1.18.2 Maven package
      id: cacheCliffs
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.18.2-all
          restore-keys: ${{ runner.os }}-spigot-1.18.2-all
    - name: Cache 1.19 Maven package
      id: cacheWild
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.19-all
          restore-keys: ${{ runner.os }}-spigot-1.19-all
    - name: Cache 1.19.3 Maven package
      id: cacheChat
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.19.3-all
          restore-keys: ${{ runner.os }}-spigot-1.19.3-all
    - name: Cache 1.19.4 Maven package
      id: cacheCreative
      uses: actions/cache@v2
      with:
          path: |
              ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.19.4-all
          restore-keys: ${{ runner.os }}-spigot-1.19.4-all
    - name: Cache 1.20 Maven package
      id: cacheTrails
      uses: actions/cache@v2
      with:
          path: |
              ~/.m2/repository/org/spigotmc/spigot/1.20-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.20-all
          restore-keys: ${{ runner.os }}-spigot-1.20-all
    - uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "tippie-repo",
                "username": "${{ secrets.TIPPIE_REPO_USERNAME }}",
                "password": "${{ secrets.TIPPIE_REPO_PASSWORD }}"
            }]
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/
